# Cấu hình giao diện
APP_SETTINGS = {
    "page_title": "Thai Giáo Cùng Như Ý",
    "page_icon": "👼",
    "main_title": "🌸 Góc Thai Giáo Của Như Ý 🌸",
    "subtitle": "Mỗi ngày một câu chuyện nhỏ, gửi gắm tình yêu to lớn cho thiên thần của mẹ 💖"
}

# Nơi dán nội dung truyện
STORIES = {
    "🌱 Hạt Mầm Kì Diệu": """
Câu chuyện 1: Chuyến Phiêu Lưu Của Hạt Mầm Kì Diệu
Trong một khu rừng sâu thẳm, nơi những bóng cây cổ thụ to lớn vươn những cánh tay rợp lá che chở cho vạn vật, có một phép màu nhỏ bé đang say ngủ. Khu rừng ấy không ồn ào hay náo nhiệt, mà mang một vẻ đẹp tĩnh lặng, êm đềm và vô cùng bình yên. Mỗi buổi sáng, khi ánh mặt trời đầu tiên chiếu rọi qua những kẽ lá, đánh thức những giọt sương mai còn đọng trên cành, khu rừng lại ngân lên một khúc ca trong trẻo của thiên nhiên. Tiếng chim lảnh lót hót vang gọi bầy, tiếng suối chảy róc rách len lỏi qua từng khe đá, và cả tiếng gió xạc xào đùa giỡn với những chiếc lá non. Tất cả tạo nên một bản giao hưởng tuyệt diệu, êm ái như một lời ru dịu dàng dành cho sinh linh bé nhỏ đang say giấc nồng dưới lớp đất nâu mềm mại.

Đó là một hạt mầm nhỏ xíu, tròn trịa và mang trong mình một sức sống mãnh liệt. Hạt mầm đã nằm đó từ rất lâu, được đất mẹ ôm ấp vào lòng, vỗ về bằng sự ấm áp và che chở khỏi những cơn gió lạnh lẽo của mùa đông. Đất mẹ hiền hòa, lúc nào cũng dịu dàng thủ thỉ vào tai hạt mầm những câu chuyện về thế giới bao la bên trên. Mẹ đất kể về bầu trời xanh ngắt cao vời vợi, về những đám mây trắng xốp như bông lững lờ trôi, về ánh nắng mặt trời rực rỡ mang lại sự sống cho muôn loài. Hạt mầm lắng nghe những câu chuyện ấy mỗi ngày, trong lòng trào dâng một khát khao mãnh liệt được vươn mình lên, được tự mắt nhìn ngắm thế giới rực rỡ mà đất mẹ vẫn thường hay kể.

Rồi một ngày, mùa xuân ấm áp gõ cửa khu rừng. Nàng tiên mùa xuân khoác lên mình chiếc váy kết từ muôn ngàn bông hoa rực rỡ, nhẹ nhàng lướt qua từng nhành cây, ngọn cỏ. Nàng mang theo những cơn mưa phùn lất phất, mỏng manh như sương, tưới mát cho vạn vật. Những giọt mưa xuân mang theo phép màu của sự sống, nhẹ nhàng thấm sâu vào lòng đất, đánh thức hạt mầm nhỏ đang say ngủ. Hạt mầm cựa mình, cảm nhận dòng nước mát lành đang chảy tràn qua từng tế bào. Nó vươn vai một cái thật dài, cảm thấy trong mình tràn trề một nguồn năng lượng mới mẻ, mạnh mẽ chưa từng có. Lớp vỏ cứng cáp bấy lâu nay che chở cho nó bắt đầu nứt ra, nhường chỗ cho một mầm non bé xíu, xanh mướt nhú lên.

Mầm non bắt đầu cuộc hành trình vĩ đại của cuộc đời mình: vươn lên mặt đất. Đó không phải là một chặng đường dễ dàng. Mầm non phải dùng hết sức lực nhỏ bé của mình để lách qua những kẽ đất tơi xốp, đôi khi gặp phải những viên sỏi cứng đầu cản đường. Nhưng mầm non không hề nản chí. Mỗi khi cảm thấy mệt mỏi, nó lại nhớ đến lời ru của đất mẹ, nhớ đến bầu trời xanh ngắt và ánh nắng chói chang đang chờ đợi mình ở phía trên. Những rễ non cũng bắt đầu cắm sâu vào lòng đất, hút lấy những dưỡng chất tinh túy nhất để nuôi dưỡng cơ thể, giúp mầm non ngày càng cứng cáp và mạnh mẽ hơn. Mỗi centimet vươn lên là một nỗ lực phi thường, là sự kiên cường và lòng dũng cảm đáng kinh ngạc của sinh linh bé nhỏ.

Cuối cùng, sau những ngày tháng nỗ lực không ngừng nghỉ, mầm non đã chạm đến lớp đất trên cùng. Một cú hích nhẹ nhàng, và rồi, bùm! Mầm non nhỏ xíu đã phá vỡ lớp đất, tự hào vươn mình ra khỏi bóng tối, đón chào thế giới ánh sáng. Khoảnh khắc đầu tiên khi mở mắt ra, mầm non bị choáng ngợp bởi vẻ đẹp lộng lẫy của vạn vật xung quanh. Mọi thứ còn rực rỡ và tươi đẹp hơn vạn lần so với những gì đất mẹ đã kể. Bầu trời quả thực xanh thẳm và rộng lớn vô tận. Ánh nắng mặt trời dịu dàng mơn trớn trên hai chiếc lá mầm non nớt, sưởi ấm cho nó sau những ngày dài dưới lòng đất lạnh. Một cơn gió thoảng qua, mang theo hương thơm ngai ngái của đất ẩm và mùi ngòn ngọt của những bông hoa rừng. Mầm non rung rinh trong gió, như một lời chào hỏi bẽn lẽn gửi đến thế giới bao la.

Một chú bướm với đôi cánh rực rỡ sắc màu bay lượn quanh mầm non, nhẹ nhàng đậu xuống chiếc lá xanh non nớt. "Chào mừng em đến với thế giới của chúng ta, sinh linh bé nhỏ!", chú bướm cất giọng trong trẻo. "Em đã làm rất tốt. Cuộc sống ngoài này vô cùng tuyệt vời, và em sẽ trở thành một cái cây thật xinh đẹp, mang lại bóng mát và niềm vui cho mọi người". Mầm non khẽ rung rung những chiếc lá, cảm thấy vô cùng hạnh phúc và tự hào. Nó biết rằng, cuộc hành trình của mình mới chỉ bắt đầu. Nó sẽ còn phải trải qua những ngày nắng gắt, những cơn mưa rào, những đợt gió lớn, nhưng nó không sợ hãi. Bởi vì nó biết, sâu thẳm bên dưới, đất mẹ vẫn luôn ôm ấp và nuôi dưỡng nó, bầu trời bao la vẫn luôn dang tay chào đón, và xung quanh nó là vô vàn những người bạn thiên nhiên tốt bụng.

Con yêu của mẹ, con cũng giống như hạt mầm nhỏ bé và dũng cảm kia vậy. Con đang say ngủ trong vòng tay ấm áp của mẹ, được mẹ che chở, yêu thương và nuôi dưỡng từng ngày. Mỗi ngày trôi qua, con lại lớn thêm một chút, khỏe mạnh hơn một chút. Mẹ biết, con cũng đang tò mò về thế giới bên ngoài, về những âm thanh con nghe thấy, về những cái chạm nhẹ nhàng qua lớp áo của mẹ. Thế giới ngoài kia rộng lớn và nhiều màu sắc lắm con ạ. Có mặt trời ấm áp, có những vì sao lấp lánh, có tiếng chim hót líu lo và có vòng tay yêu thương của ba mẹ đang chờ đón con.

Nhưng con đừng vội vã nhé. Hãy cứ an tâm say giấc, hấp thu những dưỡng chất ngọt ngào nhất từ tình yêu của mẹ, để chuẩn bị cho mình một cơ thể thật khỏe mạnh, một trái tim thật dũng cảm. Chặng đường phía trước của con sẽ là một cuộc phiêu lưu tuyệt vời nhất. Khi nào con sẵn sàng, hãy mạnh mẽ vươn mình ra thế giới, giống như hạt mầm kiên cường đã phá vỡ lớp đất nảy mầm. Ba mẹ sẽ ở đây, ngay khoảnh khắc đầu tiên con mở mắt, để dành cho con nụ cười ấm áp nhất và cái ôm chặt nhất. Hãy lớn lên thật bình an, sinh linh bé nhỏ và kỳ diệu của ba mẹ. Mẹ yêu con rất nhiều, yêu hơn bất cứ điều gì trên thế gian này.
""",
    
    "☁️ Đám Mây Nhỏ Đi Tìm Ý Nghĩa": """
Câu chuyện 2: Đám Mây Nhỏ Đi Tìm Ý Nghĩa Cuộc Sống
Trên bầu trời cao vời vợi, nơi không gian trong vắt như một viên pha lê khổng lồ, có một gia đình mây sinh sống. Những đám mây to lớn, trắng muốt như những chiếc kẹo bông gòn lơ lửng giữa không trung. Trong gia đình ấy, có một đám mây nhỏ xíu, bé bé xinh xinh và lúc nào cũng mang trong mình vô vàn câu hỏi. Trong khi các anh chị mây lớn thích lững lờ trôi theo chiều gió, thong dong ngắm nhìn thế giới từ trên cao hay tụ tập lại thành những hình thù ngộ nghĩnh, thì đám mây nhỏ lại không ngừng băn khoăn về sự tồn tại của chính mình. "Mình sinh ra để làm gì nhỉ?", đám mây nhỏ tự hỏi. "Chẳng lẽ chỉ để lơ lửng trôi trên bầu trời mãi như thế này sao?".

Một ngày nọ, đám mây nhỏ quyết định xin phép mẹ gió để bắt đầu một cuộc hành trình đi tìm ý nghĩa cuộc sống của mình. Mẹ gió hiền từ mỉm cười, thổi một luồng hơi nhẹ nhàng đẩy đám mây nhỏ trôi đi. "Hãy đi đi con yêu, hãy dùng trái tim của mình để cảm nhận thế giới, con sẽ tìm thấy câu trả lời", mẹ gió dặn dò. Thế là đám mây nhỏ háo hức bắt đầu chuyến phiêu lưu đầu tiên. Nó trôi qua những ngọn núi cao chót vót, quanh năm tuyết phủ trắng xóa. Những đỉnh núi sắc nhọn như muốn chọc thủng bầu trời, kiêu hãnh đứng giữa đất trời. Đám mây nhỏ sà xuống thấp một chút, rụt rè hỏi: "Bác núi ơi, bác có biết cháu sinh ra để làm gì không?". Ngọn núi ầm ầm đáp lại bằng một giọng trầm đục: "Ta không biết, hỡi mây nhỏ. Nhiệm vụ của ta là đứng vững ở đây, che chắn những cơn bão và tạo ra những dòng suối từ băng tuyết tan. Trách nhiệm của mỗi loài là khác nhau, cháu phải tự mình khám phá thôi".

Đám mây nhỏ lại tiếp tục bay đi. Nó trôi qua một cánh đồng hoa hướng dương rực rỡ dưới ánh nắng mặt trời. Hàng vạn bông hoa vàng ươm đang cùng nhau ngước nhìn lên bầu trời, tạo thành một thảm màu vàng rực rỡ đến lóa mắt. Đám mây nhỏ ngẩn ngơ trước vẻ đẹp ấy, nó hỏi một bông hoa hướng dương cao lớn nhất: "Bạn hoa ơi, bạn có biết mình sinh ra để làm gì không?". Bông hoa rung rinh trong gió, đáp lại bằng một giọng thanh thúy: "Tớ sinh ra để đón ánh nắng mặt trời, để tỏa hương sắc cho đời và mang lại hạt mầm cho mùa sau. Cậu hãy thử bay đến những nơi đang cần sự giúp đỡ xem sao, biết đâu cậu sẽ tìm thấy ý nghĩa của mình ở đó". Lời khuyên của bông hoa hướng dương làm đám mây nhỏ bừng tỉnh. Nó quyết định nhờ bác gió đưa mình đến những vùng đất xa xôi hơn.

Bác gió thổi mạnh, đưa đám mây nhỏ vượt qua những cánh rừng xanh mướt, những dòng sông êm đềm, cho đến khi nó đến một vùng đất khô cằn, nứt nẻ. Ở đây, mặt trời chiếu những tia nắng chói chang, gay gắt như muốn thiêu đốt mọi thứ. Cây cối héo hon, rũ rượi, những chiếc lá vàng vọt rụng lả tả. Dưới mặt đất, những con vật nhỏ bé đang khát khô cổ, mệt mỏi nằm bẹp dưới những bóng râm nhỏ nhoi còn sót lại. Một cái cây khô héo thều thào gọi: "Nước... chúng tôi cần nước...". Trái tim của đám mây nhỏ thắt lại. Nó chưa bao giờ nhìn thấy một cảnh tượng nào đáng thương đến thế. Nó muốn giúp đỡ họ, nhưng nó chỉ là một đám mây nhỏ bé, bồng bềnh, làm sao có thể mang lại nước cho cả một vùng đất rộng lớn này?

Đúng lúc đó, đám mây nhỏ nhớ lại lời dạy của mẹ gió: "Hãy dùng trái tim của mình để cảm nhận". Nó nhắm mắt lại, dồn hết sức lực và tình yêu thương của mình, cố gắng tập trung mọi luồng không khí ẩm ướt xung quanh. Bỗng nhiên, từ một đám mây trắng xốp, nó bắt đầu chuyển sang màu xám sẫm. Nó cảm thấy cơ thể mình nặng trĩu, chứa đầy những giọt nước mát lành. Không chần chừ thêm giây phút nào, đám mây nhỏ bung mình ra, hóa thành vô vàn những hạt mưa trong vắt, tuôn rơi xuống mặt đất khô cằn.

"Mưa rồi! Mưa rồi!", muôn loài reo hò trong sung sướng. Những hạt mưa mát lạnh rơi xuống, tưới tắm cho cỏ cây, lấp đầy những khe nẻ của đất. Cây cối như bừng tỉnh sau một giấc ngủ dài, vươn những cành lá xanh tươi đón nhận dòng nước ngọt ngào. Những con vật nhỏ bé vui sướng uống những ngọn nước hiếm hoi, nhảy múa dưới cơn mưa vô cùng thích thú. Đất trời như được khoác lên một chiếc áo mới, tràn đầy sức sống và hy vọng. Đám mây nhỏ không còn tồn tại dưới hình hài một đám mây nữa, nhưng nó không hề buồn bã. Bởi vì, nó đang hòa mình vào từng cái cây, từng ngọn cỏ, từng dòng suối nhỏ. Nó đã hiểu được ý nghĩa thực sự của cuộc đời mình: đó là sự hy sinh, là mang lại sự sống và niềm vui cho muôn loài.

Con yêu của ba mẹ, câu chuyện của đám mây nhỏ cũng là một bài học tuyệt vời về tình yêu thương và sự sẻ chia. Mỗi sinh mệnh khi sinh ra trên cõi đời này đều mang một ý nghĩa đặc biệt, và ý nghĩa cao đẹp nhất chính là biết yêu thương và mang lại hạnh phúc cho những người xung quanh. Con đang lớn lên từng ngày trong cơ thể mẹ, cảm nhận được từng nhịp đập trái tim mẹ, cảm nhận được tình yêu bao la mà ba mẹ dành cho con. Tình yêu ấy giống như những giọt mưa mát lành tưới tắm cho mầm non, nuôi dưỡng con trở thành một em bé khỏe mạnh, vui vẻ và ngoan ngoãn.

Ba mẹ không mong ước gì cao xa, chỉ mong con khi sinh ra sẽ là một em bé có trái tim ấm áp, biết yêu thương muôn loài, biết chia sẻ niềm vui với những người xung quanh. Hãy giống như đám mây nhỏ, dù nhỏ bé nhưng mang trong mình một tình yêu to lớn, sẵn sàng hóa thành cơn mưa tưới mát cho những tâm hồn đang khô cằn. Nhưng trước khi làm được những điều vĩ đại đó, con hãy ngoan ngoãn nằm trong bụng mẹ nhé, ăn thật no, ngủ thật say để lớn lên cứng cáp. Ba mẹ sẽ luôn là bầu trời bao la, là ngọn gió hiền hòa, che chở và dìu dắt con trên mỗi bước đường đời. Ngủ ngoan nhé, thiên thần bé nhỏ của ba mẹ. Cả thế giới đang mong chờ ngày con chào đời, mang theo ánh sáng và tình yêu thương đến với gia đình chúng ta.
""",
    
    "🌊 Bản Giao Hưởng Đại Dương": """
Câu chuyện 3: Bản Giao Hưởng Của Đại Dương Xanh
Sâu thẳm dưới những con sóng bạc đầu của đại dương bao la, có một thế giới bí ẩn và tuyệt diệu ẩn mình. Đó không phải là một thế giới tối tăm và tĩnh lặng như nhiều người vẫn tưởng tượng, mà là một vương quốc vô cùng rực rỡ, tràn ngập ánh sáng, màu sắc và những âm thanh kỳ diệu. Dưới tầng nước trong vắt như pha lê, ánh nắng mặt trời xuyên qua tạo thành những dải ánh sáng lung linh, nhảy múa trên những rặng san hô nhiều màu sắc. San hô đỏ chót như những cụm hoa nở rộ, san hô xanh biếc như những tán cây dưới nước, san hô tím mộng mơ đung đưa theo từng nhịp sóng. Chúng tạo thành một khu rừng dưới đáy biển, nơi trú ngụ của hàng ngàn loài sinh vật biển với muôn hình vạn trạng.

Trong vương quốc đại dương ấy, có một chú cá Heo nhỏ tên là Fin. Fin là một chú cá Heo vô cùng thông minh, hiếu động và có một đôi mắt to tròn, lấp lánh như hai hòn bi ve. Khác với những người bạn cùng trang lứa chỉ thích đuổi bắt nhau quanh những rặng san hô, Fin lại có một niềm đam mê mãnh liệt với những âm thanh. Chú yêu thích tiếng nước chảy róc rách qua các khe đá, tiếng cọ xát nhẹ nhàng của những chiếc vỏ sò trên bãi cát trắng, và đặc biệt là tiếng hát du dương của bác Cá Voi xanh vọng lại từ phương xa. Đối với Fin, mỗi âm thanh dưới đại dương đều là một nốt nhạc tuyệt vời, và chú luôn ao ước có thể tạo ra một bản giao hưởng trọn vẹn của riêng mình.

Một ngày nọ, Fin quyết định sẽ tổ chức một buổi hòa nhạc lớn nhất từ trước đến nay để dành tặng cho nữ hoàng Biển Cả nhân ngày sinh nhật của bà. Chú bơi khắp nơi, mời gọi những người bạn tài năng nhất trong vương quốc đại dương tham gia vào ban nhạc của mình. Đầu tiên, Fin đến gặp anh bạn Tôm Hùm gai góc. Dù vẻ ngoài có vẻ bặm trợn, nhưng Tôm Hùm lại có đôi càng gõ nhịp cực kỳ điêu luyện. "Anh Tôm Hùm ơi, anh có muốn tham gia vào ban nhạc của em không? Những nhịp gõ của anh chắc chắn sẽ làm nền tảng vững chắc cho bản giao hưởng của chúng ta đấy!", Fin hào hứng nói. Tôm Hùm đồng ý ngay lập tức, vung vẩy đôi càng tạo ra những tiếng "lách cách" vui tai.

Tiếp theo, Fin mời bầy Cá Ngựa tham gia. Những chú cá ngựa nhỏ bé, với chiếc đuôi xoắn ốc xinh xắn, có khả năng di chuyển lên xuống vô cùng nhịp nhàng. Chúng sẽ hóa thân thành những vũ công điệu nghệ, tạo ra những âm thanh vút cao như tiếng đàn vĩ cầm khi lướt qua những luồng nước. Rồi Fin tìm đến những cô Sứa biển mềm mại, trong suốt. Những chiếc tua dài của các cô Sứa khi khẽ chạm vào nhau tạo ra những âm thanh rinh rích, mờ ảo như tiếng chuông gió ngân vang trong buổi chiều tà. Cuối cùng, để bản giao hưởng thêm phần hoành tráng, Fin đã dũng cảm bơi ra vùng nước sâu, kính cẩn mời bác Cá Voi xanh tham gia bằng giọng hát trầm ấm, vang vọng xuyên đại dương của mình.

Những ngày sau đó, cả ban nhạc dưới sự chỉ huy của nhạc trưởng Fin ngày đêm tập luyện say sưa. Ban đầu, mọi thứ còn khá lộn xộn. Tiếng gõ càng của anh Tôm Hùm đi lệch nhịp với bầy Cá Ngựa, còn giọng hát của bác Cá Voi xanh thì lại át mất tiếng chuông gió mỏng manh của các cô Sứa. Nhưng Fin không hề nản lòng. Bằng sự kiên nhẫn, tình yêu âm nhạc và tài năng chỉ huy của mình, chú dần dần kết nối mọi người lại với nhau. Chú lắng nghe từng âm thanh, điều chỉnh từng nhịp điệu, giúp các thành viên thấu hiểu và hòa quyện vào nhau. Chẳng bao lâu sau, những âm thanh rời rạc đã biến thành một bản nhạc hoàn chỉnh, êm ái, sâu lắng nhưng cũng vô cùng hùng tráng và tráng lệ.

Ngày sinh nhật của nữ hoàng Biển Cả cũng đến. Toàn bộ cư dân của vương quốc đại dương đều tụ tập đông đủ tại quảng trường San Hô để thưởng thức buổi hòa nhạc. Khi Fin đưa chiếc vây nhỏ của mình lên, báo hiệu bắt đầu, cả đại dương dường như chìm vào tĩnh lặng. Rồi từ từ, những nhịp gõ chắc nịch của anh Tôm Hùm vang lên, nhịp nhàng và lôi cuốn. Tiếp đó là sự tham gia của bầy Cá Ngựa, mang đến những giai điệu vui tươi, rộn rã. Các cô Sứa biển nhẹ nhàng điểm xuyết những tiếng chuông ngân nga, thanh thúy. Và cuối cùng, giọng hát trầm hùng, ấm áp của bác Cá Voi xanh vang lên, ôm trọn lấy tất cả mọi âm thanh, tạo nên một bản giao hưởng vĩ đại, lay động mọi trái tim. Bản nhạc kể về vẻ đẹp của đại dương, về tình yêu thương, sự đoàn kết và niềm vui của cuộc sống. Nữ hoàng Biển Cả xúc động rơi những giọt nước mắt trân châu rực rỡ, bà khen ngợi Fin và ban nhạc đã mang đến món quà tuyệt vời nhất.

Con yêu của mẹ, con có đang lắng nghe bản giao hưởng của sự sống ngay lúc này không? Trong thế giới tĩnh lặng bên trong bụng mẹ, con cũng đang được đắm mình trong những âm thanh kỳ diệu. Đó là tiếng nhịp tim đập thình thịch, mạnh mẽ và đều đặn của mẹ, giống như những nhịp gõ vững chãi của anh Tôm Hùm, báo hiệu sự sống đang tuôn chảy không ngừng. Đó là tiếng dòng máu chảy qua các huyết quản, êm đềm như tiếng bầy Cá Ngựa lướt đi trong nước. Và đó còn là tiếng thủ thỉ dịu dàng, tiếng hát ru êm ái của ba mẹ mỗi đêm, giống như giọng hát ấm áp của bác Cá Voi xanh, bao bọc và chở che con khỏi mọi bão giông.

Những âm thanh ấy chính là bản giao hưởng tuyệt vời nhất mà ba mẹ dành riêng cho con, để nuôi dưỡng tâm hồn con trở nên phong phú, nhạy cảm và tràn đầy tình yêu thương. Ba mẹ muốn con biết rằng, dù thế giới ngoài kia có ồn ào và náo nhiệt đến đâu, thì trong trái tim ba mẹ, con luôn là giai điệu êm ái nhất, bình yên nhất. Hãy cứ nhắm mắt lại, thư giãn và tận hưởng bản nhạc của tình mẫu tử, tình phụ tử thiêng liêng này con nhé. Mỗi một ngày trôi qua, bản giao hưởng ấy sẽ càng trở nên mạnh mẽ và rõ ràng hơn, chào đón ngày con cất tiếng khóc chào đời, gia nhập vào dàn đồng ca rực rỡ của cuộc sống. Ngủ ngon nhé, nhạc trưởng tài ba bé nhỏ của ba mẹ!
""",
    "✨ 4. Đom Đóm Nhỏ Tìm Thấy Ánh Sáng": """
Câu chuyện 4: Chú Đom Đóm Nhỏ Tìm Thấy Ánh Sáng Của Mình
Khi ông mặt trời từ từ khuất sau rặng núi xa xa, nhường chỗ cho tấm màn nhung màu xanh thẫm của màn đêm buông xuống, khu rừng Mộng Mơ bắt đầu khoác lên mình một vẻ đẹp huyền bí. Bầu trời đêm quang đãng, điểm xuyết hàng vạn vì sao lấp lánh như những viên kim cương được rải đều trên tấm thảm khổng lồ. Chị Hằng Nga xuất hiện với nụ cười dịu dàng, tỏa ánh sáng bàng bạc, dịu mát xuống muôn loài. Lúc này, những cư dân của bóng đêm mới bắt đầu thức giấc. Trong số đó, có một gia đình nhà Đom Đóm sinh sống dưới gốc cây sồi già.

Chú Đom Đóm Nhỏ của chúng ta tên là Lấp Lánh. Lấp Lánh là một chú đom đóm ngoan ngoãn, đáng yêu, nhưng dạo gần đây, chú lại hay mang một nỗi buồn vu vơ. Mỗi khi đêm xuống, nhìn lên bầu trời, Lấp Lánh thấy ánh trăng thật vĩ đại, chiếu sáng cả một vùng không gian rộng lớn. Những vì sao dẫu ở xa tít tắp cũng có thể vươn những tia sáng lấp lánh của mình xuống mặt đất. Rồi nhìn lại chiếc bụng nhỏ bé của mình, Lấp Lánh chỉ thấy một đốm sáng màu vàng chanh leo lét, bé xíu. Đốm sáng ấy mờ nhạt đến mức chỉ soi rõ được một chiếc lá hay một cánh hoa bé mọn. Lấp Lánh thở dài thườn thượt, giấu mình vào mặt dưới của một chiếc lá dương xỉ, tự hỏi: "Ánh sáng của mình nhỏ bé và yếu ớt thế này, thì có ích lợi gì cơ chứ? Mình chẳng thể soi sáng cả khu rừng như chị Hằng, cũng chẳng thể làm bầu trời rực rỡ như các vì sao".

Thấy con trai buồn bã, mẹ Đom Đóm bay đến, nhẹ nhàng đậu xuống bên cạnh. Mẹ dùng đôi cánh mỏng manh xoa xoa lưng Lấp Lánh, âu yếm nói: "Con trai bé bỏng của mẹ, mỗi ánh sáng trên thế gian này đều mang một sứ mệnh riêng. Ánh trăng soi đường cho những đàn chim di cư bay trong đêm, ánh sao giúp các bác thủy thủ ngoài đại dương không bị lạc lối. Còn ánh sáng của con, dù nhỏ bé, nhưng lại mang một sự ấm áp rất đỗi diệu kỳ. Con hãy bay ra ngoài kia, dùng trái tim để cảm nhận, con sẽ thấy ánh sáng của mình quý giá đến nhường nào".

Nghe lời mẹ, Lấp Lánh rụt rè cất cánh. Chú bay là là trên mặt cỏ đẫm sương đêm. Bỗng nhiên, chú nghe thấy tiếng khóc thút thít phát ra từ dưới một gốc nấm hương. Lấp Lánh bay lại gần, soi chiếc đèn nhỏ xíu của mình xuống. Hóa ra đó là một bé Kiến thợ đang bị lạc đường. Bé Kiến vác trên lưng một hạt gạo to đùng, nước mắt lưng tròng: "Hu hu, tối quá, cháu không nhìn thấy đường về tổ. Mẹ cháu chắc đang lo lắng lắm". Lấp Lánh thấy vậy, liền bay thấp xuống, bay ngay phía trước bé Kiến thợ. "Đừng khóc nữa bé Kiến, anh sẽ dùng chiếc đèn của anh để soi đường cho em nhé. Cứ đi theo vệt sáng màu vàng này, chúng ta sẽ tìm được đường về nhà". Ánh sáng của Lấp Lánh tuy nhỏ, nhưng ở khoảng cách gần, nó soi rõ từng hòn sỏi, từng cọng cỏ, giúp bé Kiến thợ tránh được những vũng nước đọng. Một lát sau, cả hai đã về đến cửa tổ kiến. Bác Kiến chúa ra đón con, rối rít cảm ơn Lấp Lánh. Đốm sáng bé nhỏ lúc này bỗng bừng lên một niềm vui ấm áp.

Lấp Lánh tiếp tục bay đi. Khi ngang qua một khóm hoa cúc dại, chú lại nghe thấy tiếng run rẩy. Một chú Sâu Non đang cuộn tròn mình dưới chiếc lá. Sâu Non sợ bóng tối, những bóng râm của cành cây in xuống mặt đất trông như những con quái vật đáng sợ khiến chú không tài nào ngủ được. Lấp Lánh nhẹ nhàng đậu xuống chiếc lá bên cạnh Sâu Non. Chú dùng hết sức, để chiếc bụng của mình phát ra ánh sáng vàng êm dịu nhất, ấm áp nhất. Ánh sáng ấy xua tan đi bóng tối đen ngòm xung quanh khóm hoa. "Đừng sợ Sâu Non, có anh ở đây rồi. Em hãy nhìn xem, những bóng đen kia chỉ là cành cây thôi. Anh sẽ ở đây soi sáng cho em ngủ nhé". Dưới ánh sáng êm đềm, vàng óng như mật ong của Lấp Lánh, Sâu Non cảm thấy an toàn tuyệt đối. Chú từ từ nhắm mắt lại, chìm vào giấc ngủ say sưa với một nụ cười mỉm trên môi.

Đêm đó, Lấp Lánh đã dùng ánh sáng nhỏ bé của mình để soi đường cho một chú ếch tìm thấy ao nước, vỗ về một nụ hoa đang chớm nở trong sương lạnh. Khi bình minh sắp ló dạng, Lấp Lánh bay về tổ dưới gốc cây sồi già. Chú không còn cảm thấy buồn bã hay tự ti nữa. Chú hiểu lời mẹ nói rồi. Ánh trăng soi sáng cả thế giới rộng lớn, nhưng ánh sáng của đom đóm lại mang đến sự an ủi, sự giúp đỡ và tình yêu thương chân thành ở cự ly gần nhất. Ánh sáng ấy sưởi ấm những trái tim đang lạc lõng, sợ hãi trong đêm tối.

Con yêu của mẹ Như Ý, đôi khi chúng ta cứ mải mê ngước nhìn những điều lớn lao, kỳ vĩ mà quên mất rằng, những điều nhỏ bé, giản dị mới thực sự mang lại hạnh phúc. Từ ngày có con xuất hiện trong bụng mẹ, con giống như một chú đom đóm nhỏ xíu, thắp lên một thứ ánh sáng rực rỡ và ấm áp nhất trong trái tim mẹ Như Ý và ba. Ánh sáng ấy không cần phải chói lóa như mặt trời, nhưng nó xua tan mọi mệt mỏi, lo âu của cuộc sống thường ngày. Mỗi cái đạp nhẹ của con, mỗi lần mẹ xoa tay lên bụng, mẹ lại thấy ánh sáng của tình mẫu tử bừng lên mãnh liệt. Con chính là ngọn đèn nhỏ kỳ diệu nhất của cuộc đời mẹ. Hãy lớn lên từng ngày thật khỏe mạnh, sáng trong và ấm áp nhé, thiên thần đom đóm của mẹ Như Ý.
""",
    "🍂 5. Chuyến Tàu Mùa Thu Của Nhím Xù": """
Câu chuyện 5: Chuyến Tàu Mùa Thu Của Bạn Nhím Xù
Trong khu rừng Hạnh Phúc, nơi những loài động vật sống chan hòa và yêu thương lẫn nhau, có một sự thay đổi kỳ diệu đang diễn ra. Bác Mặt Trời không còn tỏa ánh nắng gay gắt như mùa hè nữa, mà thay vào đó là những tia nắng vàng ươm, dịu ngọt rải rác qua từng tán lá. Chị Gió cũng trở nên mát mẻ hơn, mang theo hương thơm ngai ngái của đất ẩm và mùi ngòn ngọt của quả chín. Mùa thu đã về! Mùa thu về mang theo một chiếc áo mới khổng lồ lấp lánh sắc vàng, sắc đỏ, sắc cam khoác lên khắp cả khu rừng. Những chiếc lá phong chuyển sang màu đỏ rực như những ngọn lửa nhỏ, lá bạch dương lại ánh lên màu vàng tươi của ánh nắng, cứ mỗi lần gió thổi qua là chúng lại lìa cành, xoay tít trong không trung như những vũ công ballet đang biểu diễn điệu múa cuối cùng trước khi chạm đất.

Dưới gốc cây dẻ sồi to lớn, có một bạn Nhím Xù đang tất bật chuẩn bị cho mùa đông sắp tới. Nhím Xù có một thân hình tròn xoe, khoác trên lưng vô vàn những chiếc gai nhọn hoắt. Dù bề ngoài trông có vẻ gai góc, nhưng bên trong, Nhím Xù lại là một cậu bé vô cùng hiền lành, ấm áp và tốt bụng. Mùa thu đối với Nhím Xù là mùa bận rộn nhất nhưng cũng là mùa vui nhất trong năm. Nhiệm vụ của cậu là phải thu thập thật nhiều thức ăn ngon và tìm những vật liệu mềm mại nhất để lót ổ, chuẩn bị cho một giấc ngủ đông thật dài và ấm áp.

Sáng sớm hôm ấy, Nhím Xù khoác chiếc giỏ mây nhỏ xíu lên lưng, bắt đầu chuyến hành trình đi gom nhặt mùa thu. Cậu đi từng bước lạch bạch, chiếc mũi nhỏ xíu ươn ướt không ngừng chun lại, hít hà mùi hương của khu rừng. A! Kia rồi! Dưới gốc cây sồi lớn, những quả sồi nâu bóng, mập mạp nằm vương vãi trên nền cỏ khô. Nhím Xù mừng rỡ, dùng hai chân trước thoăn thoắt nhặt từng quả sồi bỏ vào giỏ. Chẳng mấy chốc, chiếc giỏ đã nặng trĩu. Cậu lại tiếp tục đi sâu vào rừng. Gió thu nhè nhẹ thổi, mang theo một quả táo đỏ au, chín mọng rơi rụng ngay trước mặt Nhím Xù. Cậu vui sướng cắm quả táo lên những chiếc gai trên lưng mình. Trông cậu lúc này chẳng khác nào một toa tàu chở đầy những thức quà ngọt ngào của mùa thu, chầm chậm lăn bánh qua những vạt rừng.

Đang mải mê nhặt nhạnh, Nhím Xù nghe thấy tiếng thở dài thườn thượt từ bụi cây mâm xôi. Cậu rẽ lá bước vào thì thấy bạn Thỏ Trắng đang ủ rũ ngồi đó. "Thỏ Trắng ơi, sao bạn lại buồn bã thế giữa một ngày mùa thu đẹp tuyệt này?", Nhím Xù hỏi. Thỏ Trắng cụp đôi tai dài xuống, buồn rầu đáp: "Mùa đông sắp đến rồi, nhưng tớ chưa tìm được củ cà rốt hay hạt dẻ nào để dự trữ cả. Tớ sợ mùa đông năm nay sẽ đói và lạnh lắm". Nghe vậy, Nhím Xù không ngần ngại, cậu tháo chiếc giỏ mây xuống, chia cho Thỏ Trắng một nửa số hạt sồi và cả quả táo đỏ trên lưng mình. "Bạn đừng lo, tớ có nhiều lắm. Chúng ta cùng chia sẻ nhé, mùa đông sẽ không còn lạnh lẽo nếu chúng ta no bụng". Thỏ Trắng cảm động đến rơi nước mắt, rối rít cảm ơn người bạn tốt bụng.

Tiếp tục hành trình, Nhím Xù lại bắt gặp Sóc Nâu đang hì hục cố gắng kéo một chùm lá phong khô ráo, mềm mại về hốc cây để lót ổ, nhưng Sóc Nâu bé quá, kéo mãi mà chùm lá cứ vướng vào cành cây. Nhím Xù lại chạy đến, dùng những chiếc gai của mình cắm vào chùm lá, dễ dàng kéo nó về tận hốc cây cho Sóc Nâu. Để đáp lại lòng tốt của Nhím Xù, Sóc Nâu đã tặng cậu một nắm hạt dẻ cười thơm lừng mà sóc vừa tìm được.

Chiều buông xuống, Nhím Xù trở về chiếc hang nhỏ của mình dưới rễ cây. Tuy chiếc giỏ mây không còn đầy ắp như lúc ban trưa, nhưng trái tim Nhím Xù lại tràn ngập niềm vui và sự ấm áp. Cậu bắt đầu lót ổ bằng những chiếc lá khô mềm mại, xếp hạt dẻ và những quả sồi còn lại vào một góc thật ngay ngắn. Chiếc hang bé xíu giờ đây đã trở thành một tổ ấm tuyệt vời, sực nức mùi thơm của trái cây mùa thu và mùi của tình bạn chân thành. Nhím Xù cuộn tròn mình lại giữa lớp lá êm ái, nhắm mắt lại mỉm cười, sẵn sàng cho một giấc ngủ đông bình yên. Cậu biết rằng, mùa đông ngoài kia dẫu có bão tuyết sương giá đến đâu, thì trong tổ ấm này, và trong trái tim của những người bạn, vẫn luôn tràn ngập hơi ấm mùa xuân.

Mẹ Như Ý đang nhẹ nhàng xoa bụng, con yêu có cảm nhận được hơi ấm truyền qua tay mẹ không? Giống như bạn Nhím Xù đang cần mẫn lót một chiếc ổ êm ái, mẹ Như Ý và ba cũng đang từng ngày, từng giờ chuẩn bị mọi thứ tốt nhất, ấm áp nhất để chào đón con ra đời. Cơ thể mẹ chính là chiếc tổ an toàn nhất, êm ái nhất của con lúc này. Mẹ đang nạp những dòng dinh dưỡng ngọt ngào nhất, giữ cho tinh thần luôn vui vẻ, bình an để con có một không gian phát triển tuyệt vời nhất.

Nhưng con biết không, điều quý giá nhất mà Nhím Xù tìm được trong mùa thu không phải là quả sồi hay hạt dẻ, mà là tình yêu thương và sự sẻ chia. Ba mẹ cũng vậy, ba mẹ đang dành cho con một tình yêu thương vô bờ bến. Tình yêu ấy lớn hơn cả bầu trời, ấm hơn cả nắng thu, đủ sức che chở cho con trước mọi cơn gió lạnh của cuộc đời. Con hãy cứ yên tâm say ngủ, ngoan ngoãn lớn lên trong chiếc tổ ấm áp của mẹ Như Ý nhé. Cả nhà mình đang đếm từng ngày để được ôm "chú nhím nhỏ" đáng yêu của ba mẹ vào lòng.

""",
    
    "🌈 6. Giọt Sương Mai Khám Phá Cầu Vồng": """
Câu chuyện 6: Giọt Sương Mai Khám Phá Chiếc Áo Cầu Vồng
Trong một khu vườn ngập tràn hương sắc, nơi những nụ hồng chúm chím, những đóa cẩm tú cầu kiêu sa và những khóm cúc họa mi mộc mạc cùng nhau khoe sắc, có một điều kỳ diệu thường chỉ xuất hiện vào lúc chạng vạng rạng đông. Đó là lúc màn đêm rục rịch rút lui, để lại trên những tán lá, ngọn cỏ những viên ngọc trong suốt, tinh khiết vô ngần. Đó chính là những giọt sương mai.

Giọt Sương Nhỏ của chúng ta được sinh ra vào lúc nửa đêm, từ một làn hơi nước mát lạnh ngưng tụ lại, dịu dàng đậu trên đầu một chiếc lá sen bọc lớp lông tơ mịn màng. Giọt Sương Nhỏ có hình dáng tròn vo, trong vắt như một viên pha lê không tì vết. Trong sự tĩnh lặng của vạn vật khi còn đang say ngủ, Giọt Sương Nhỏ im lìm nằm đó, lắng nghe nhịp đập của đất trời. Khi những tia sáng đầu tiên của ngày mới bắt đầu ửng hồng phía chân trời, khu vườn dần dần thức tỉnh. Những bông hoa thi nhau bung nở, vươn mình phô diễn những màu sắc rực rỡ nhất để chào đón mặt trời. Hoa hồng tự hào với chiếc váy đỏ thắm kiêu kỳ, hoa hướng dương rạng rỡ với sắc vàng ươm như nắng, hoa oải hương mộng mơ trong sắc tím dịu dàng.

Giọt Sương Nhỏ nhìn những người bạn xung quanh, rồi lại nhìn xuống bản thân mình. Chú thấy mình sao mà đơn điệu và nhàm chán quá. "Mình chẳng có màu đỏ của hoa hồng, chẳng có màu vàng rực rỡ của hướng dương, mình chỉ là một giọt nước trong vắt, không có màu sắc gì cả", Giọt Sương Nhỏ buồn bã nghĩ. Chú cảm thấy mình thật bé nhỏ và vô hình giữa thế giới đầy màu sắc huy hoàng này. Chú chỉ muốn cuộn mình lại thật chặt, trốn vào những gân lá để không ai nhìn thấy sự nhạt nhòa của mình.

Thấy Giọt Sương Nhỏ ủ rũ, bác Gió bay ngang qua liền nhẹ nhàng thổi một luồng hơi mát lạnh, lay động chiếc lá sen. "Giọt Sương bé nhỏ ơi, cháu đừng buồn bã thế", bác Gió thì thầm trầm ấm. "Cháu không vô hình, và cháu cũng không hề nhạt nhòa. Vẻ đẹp của cháu đang được cất giấu ở bên trong, và nó cần đúng thời điểm để tỏa sáng rực rỡ nhất. Hãy kiên nhẫn chờ đợi, khi ánh mặt trời thức dậy hoàn toàn, cháu sẽ thấy điều kỳ diệu". Giọt Sương Nhỏ bán tín bán nghi, nhưng cũng cố gắng ngoan ngoãn nằm im, ngước ánh mắt trong veo chờ đợi.

Rồi khoảnh khắc kỳ diệu ấy cũng đến. Ông Mặt Trời vươn vai thức dậy, vén bức màn mây xám xịt, rọi những tia nắng vàng rực rỡ, ấm áp xuống mặt đất. Một tia nắng mai tinh nghịch xuyên qua kẽ lá, chiếu thẳng vào Giọt Sương Nhỏ. Bất chợt, một phép thuật lạ thường xảy ra! Cơ thể trong suốt của Giọt Sương Nhỏ khi đón nhận tia nắng bỗng nhiên không còn vô hình nữa. Tia sáng đi qua giọt nước, bị uốn cong và tách ra thành vô vàn những luồng ánh sáng rực rỡ. Từ một giọt nước không màu, Giọt Sương Nhỏ bỗng bừng sáng, khoác lên mình một chiếc áo lộng lẫy bao gồm cả bảy sắc cầu vồng: Đỏ, cam, vàng, lục, lam, chàm, tím.

Chiếc áo cầu vồng lung linh lấp lánh, phản chiếu ánh sáng lộng lẫy đến mức khiến cả những đóa hoa hồng, hoa cúc xung quanh cũng phải ngỡ ngàng thán phục. "Ôi, cậu đẹp quá Giọt Sương ơi!", bông hoa họa mi reo lên. "Cậu mang trên mình màu sắc của tất cả chúng tớ gộp lại cơ đấy!". Giọt Sương Nhỏ lúc này mới ngỡ ngàng nhận ra giá trị của bản thân. Chú nhận ra rằng, sự trong suốt, tinh khiết của mình không phải là sự tẻ nhạt, mà chính là khả năng dung nạp và phản chiếu mọi vẻ đẹp rực rỡ nhất của ánh sáng mặt trời. Chú không cần phải cố gắng giống một màu sắc cụ thể nào, bởi tự thân chú đã mang trong mình tiềm năng để tạo ra một chiếc cầu vồng tuyệt diệu. Chú rung rinh chiếc bụng tròn xoe, kiêu hãnh lấp lánh trên chiếc lá sen, vui vẻ mỉm cười với thế giới muôn màu xung quanh.

Bé cưng của mẹ Như Ý ơi, câu chuyện của Giọt Sương Nhỏ thật kỳ diệu phải không con? Mỗi em bé sinh ra trên đời đều giống như một giọt sương mai trong trẻo, tinh khiết và mang trong mình một vẻ đẹp tiềm ẩn vô cùng lớn lao. Có thể bây giờ con chỉ là một hình hài bé nhỏ đang tượng hình trong bụng mẹ, nhưng con biết không, con chính là sự kết tinh hoàn hảo nhất của tình yêu thương.

Mẹ Như Ý không kỳ vọng con phải trở thành một ai đó xuất chúng hay hoàn hảo theo ý người khác. Mẹ chỉ mong con luôn giữ được tâm hồn trong trẻo, thánh thiện như giọt sương kia. Dưới ánh sáng của tình yêu thương, sự giáo dục và dìu dắt của ba mẹ, mẹ tin chắc rằng con sẽ phát huy được hết những tiềm năng tuyệt vời nhất bên trong mình, và tự khoác lên mình một chiếc áo cầu vồng rực rỡ mang tên hạnh phúc và thành công. Mỗi bước ngoặt, mỗi sự phát triển của con sẽ mang đến những màu sắc tươi đẹp nhất cho bức tranh gia đình mình. Mẹ Như Ý yêu con, giọt sương nhỏ bé và lấp lánh của đời mẹ!
""",
    
    "🍯 7. Chú Gấu Con Học Cách Kiên Nhẫn": """
Câu chuyện 7: Chú Gấu Con học cách kiên nhẫn
Sâu trong khu rừng thông rậm rạp, nơi những thân cây cao vút vươn thẳng lên bầu trời như những cây cột chống đỡ vòm mây, có một gia đình nhà gấu đang rục rịch chuẩn bị cho kỳ ngủ đông. Gấu Mẹ với bộ lông nâu óng ả đang bận rộn thu thập những cành cây khô, rêu mềm và những lớp lá rụng dày đặc để lót ổ bên trong một hang đá rộng rãi. Trong khi đó, Gấu Con – một chú gấu nhỏ tròn xoe, hiếu động – lại cứ chạy lăng xăng quanh miệng hang. Mùa thu năm nay mang theo những cơn gió lạnh buốt từ phương Bắc sớm hơn mọi khi, báo hiệu một mùa đông dài và khắc nghiệt. Nhưng Gấu Con dường như chẳng bận tâm đến cái lạnh. Tâm trí chú lúc này chỉ ngập tràn hình ảnh của những hũ mật ong vàng óng, ngọt ngào.

Số là vài ngày trước, Gấu Con đã tình cờ phát hiện ra một tổ ong khổng lồ nằm ẩn mình trên một cành sồi già trơ trọi lá. Tổ ong sẫm màu, tỏa ra một mùi hương ngòn ngọt, quyến rũ đến mức chỉ cần hít một hơi, Gấu Con đã cảm thấy bụng mình sôi lên ùng ục. Chú đã nài nỉ Gấu Mẹ cho phép mình trèo lên lấy mật, nhưng Gấu Mẹ lại lắc đầu ân cần từ chối. "Chưa được đâu con yêu," Gấu Mẹ nói, giọng trầm ấm vang lên giữa không gian tĩnh lặng của khu rừng. "Bây giờ bầy ong đang rất hung dữ vì chúng cũng cần bảo vệ nguồn thức ăn cuối cùng để vượt qua mùa đông. Hơn nữa, mật ong lúc này chưa đạt đến độ ngon nhất. Chúng ta phải đợi".

Nhưng Gấu Con vốn là một chú gấu thiếu kiên nhẫn. Những lời giải thích của mẹ dường như không lọt vào tai chú. Cứ mỗi lần nhắm mắt lại để cố dỗ giấc ngủ đông, mùi hương ngọt ngào của tổ ong lại xộc vào mũi, đánh thức mọi giác quan. Một đêm nọ, khi tiếng thở đều đặn của Gấu Mẹ đã vang lên đều đặn trong hang đá ấm áp, Gấu Con lặng lẽ lẻn ra ngoài. Gió bấc thổi từng cơn lạnh thấu xương, những bông tuyết đầu mùa bắt đầu rơi lả tả, phủ trắng xóa cả một vùng. Gấu Con run rẩy trèo lên cây sồi già. Nhưng vừa chạm móng vuốt vào lớp vỏ ngoài của tổ ong, một bầy ong thợ đang cảnh giác đã bay ra, chích những mũi kim đau điếng vào chiếc mũi ươn ướt của Gấu Con. Chú đau đớn kêu ré lên, trượt chân ngã uỵch xuống lớp tuyết dày và phải chạy trối chết về hang, chui rúc vào vòng tay ấm áp của mẹ, khóc thút thít.

Gấu Mẹ tỉnh giấc, nhẹ nhàng ôm Gấu Con vào lòng, dùng chiếc lưỡi ấm áp liếm láp vết ong đốt trên mũi con. "Con thấy không, vội vàng không bao giờ mang lại kết quả tốt đẹp," Gấu Mẹ dịu dàng thủ thỉ. "Thiên nhiên có nhịp điệu riêng của nó. Có những thứ cần phải có thời gian để ủ chín, để trở nên hoàn hảo. Kiên nhẫn không phải là sự chờ đợi nhàm chán, mà là sự nuôi dưỡng hy vọng. Con hãy yên tâm đi ngủ. Khi mùa xuân đến, vạn vật thức giấc, những bông hoa đầu tiên hé nở, bầy ong sẽ lại bận rộn đi lấy mật mới. Lúc đó, mật ong trong tổ sẽ là thứ mật thơm ngon nhất, tinh túy nhất mà con từng được nếm". Gấu Con ngoan ngoãn gật đầu, rúc sâu vào lớp lông ấm áp của mẹ, nhắm mắt lại. Lần này, chú không còn mơ thấy sự vội vã, mà mơ về những vạt nắng vàng ươm của mùa xuân sắp tới.

Thời gian chầm chậm trôi qua. Gấu Con chìm trong giấc ngủ dài, lắng nghe tiếng gió rít gào bên ngoài cửa hang, lắng nghe tiếng tuyết rơi dày trên những cành thông. Rồi một ngày, một luồng không khí ấm áp len lỏi vào tận đáy hang. Băng tuyết bắt đầu tan chảy, tạo thành những dòng suối nhỏ róc rách hát ca. Mùi của đất ẩm, mùi của chồi non đang nhú và mùi của những nụ hoa rừng thoang thoảng đánh thức hai mẹ con. Gấu Con vươn vai một cái thật dài, cảm thấy cơ thể tràn trề sức sống. Gấu Mẹ mỉm cười dẫn con ra khỏi hang. Cả khu rừng như được thay một lớp áo mới rực rỡ và tươi tắn. Và đúng như lời mẹ nói, trên cành sồi già, tổ ong giờ đây căng mọng. Bầy ong hiền hòa bay lượn xung quanh những khóm hoa mới nở, không còn hung dữ bảo vệ tổ nữa. Gấu Mẹ nhẹ nhàng lấy xuống một tảng sáp ong vàng ươm, đặc quánh mật ngọt đưa cho Gấu Con. Nếm thử miếng mật ong đầu tiên của mùa xuân, Gấu Con nhắm nghiền mắt lại tận hưởng. Quả thực, vị ngọt lịm, thanh mát và hương thơm hoa cỏ đọng lại trên đầu lưỡi ngon hơn gấp ngàn lần so với những gì chú từng tưởng tượng. Đó là phần thưởng xứng đáng cho một sự chờ đợi kiên cường.

Bé cưng của mẹ Như Ý ơi, câu chuyện của chú Gấu Con cũng giống như hành trình mà mẹ và ba đang trải qua lúc này vậy. Chờ đợi một thiên thần nhỏ chào đời là một khoảng thời gian dài, đòi hỏi sự kiên nhẫn tuyệt đối. Đôi khi, mẹ Như Ý cũng cảm thấy thật nôn nóng, muốn được nhìn thấy khuôn mặt nhỏ nhắn của con, muốn được ôm con vào lòng ngay lập tức. Những lúc cơ thể mỏi mệt, mẹ lại ước thời gian trôi qua thật nhanh. Nhưng mẹ hiểu rằng, con cần đủ 9 tháng 10 ngày để hoàn thiện mọi tế bào, để trở nên thật khỏe mạnh và cứng cáp trước khi bước ra thế giới rộng lớn này. Khoảng thời gian con nằm trong bụng mẹ chính là khoảng thời gian con đang được "ủ ấm" bằng tất cả tình yêu thương, bằng dòng sữa ngọt ngào và những nhịp đập trái tim đầy thổn thức. Mẹ Như Ý sẽ học cách kiên nhẫn như Gấu Con, tận hưởng trọn vẹn từng khoảnh khắc được cảm nhận sự hiện diện của con trong cơ thể mình. Bởi mẹ biết, ngày con cất tiếng khóc chào đời sẽ là khoảnh khắc ngọt ngào nhất, hạnh phúc nhất, phần thưởng vô giá nhất cho sự chờ đợi của cả gia đình chúng ta.
""",
    
    "🐚 8. Chuyến Du Hành Của Hạt Cát": """
Câu chuyện 8: Chuyến du hành của Hạt Cát
Dưới đáy một dòng sông hiền hòa, nơi dòng nước trong vắt ngày đêm mải miết chảy qua những rặng thủy thảo xanh rì, có một Hạt Cát vô cùng nhỏ bé sinh sống. Hạt Cát không lớn hơn một đầu kim, mang màu vàng nâu giản dị. Xung quanh Hạt Cát là hàng triệu, hàng tỷ những hạt cát anh em khác, tất cả đều nằm im lìm dưới đáy sông, ngày qua ngày ngắm nhìn những đàn cá bơi lội tung tăng qua lại. Cuộc sống dưới đáy sông rất bình yên, an toàn nhưng lại có phần tẻ nhạt. Hầu hết các hạt cát đều bằng lòng với sự tĩnh lặng ấy, chúng tự hào vì mình là lớp đệm vững chắc cho dòng sông, giúp nước trở nên trong vắt.

Nhưng Hạt Cát của chúng ta lại khác. Trong sâu thẳm tâm hồn nhỏ bé ấy luôn cháy bỏng một khao khát được đi xa. Hạt Cát từng được nghe cụ Rùa già kể về một nơi gọi là "Đại Dương". Cụ Rùa kể rằng, Đại Dương bao la đến mức không thể nhìn thấy bến bờ, nước ở đó có màu xanh thẳm như ngọc bích, và những con sóng vỗ cuồn cuộn có thể tung bọt trắng xóa cao hàng chục thước. Nơi đó có những rặng san hô khổng lồ, có những chú cá voi to bằng cả một hòn núi, và những loài sinh vật kỳ diệu mà sông hồ không bao giờ có được. Kể từ ngày nghe câu chuyện ấy, Hạt Cát không còn muốn nằm yên một chỗ nữa. Chú quyết tâm phải thực hiện một chuyến du hành đến Đại Dương vĩ đại.

Một buổi sáng mùa hạ, khi một cơn mưa lớn trút xuống thượng nguồn, dòng sông trở nên cuộn trào mạnh mẽ hơn. Nước cuốn theo bùn đất, những nhánh cây gãy và thổi tung lớp cát dưới đáy. Chớp lấy cơ hội này, Hạt Cát buông lỏng mình, nương theo dòng chảy xiết của dòng nước. Cuộc hành trình vĩ đại bắt đầu. Ban đầu, mọi thứ thật đáng sợ. Dòng nước chảy xiết khiến Hạt Cát bị cuốn lộn vòng, va đập vào những hòn đá cuội nhẵn thính. Có lúc, chú bị dòng nước xoáy hút vào một cái hang tối tăm, tưởng chừng như không bao giờ thoát ra được. Nhưng Hạt Cát không bỏ cuộc. Chú kiên trì chờ đợi, luồn lách qua từng kẽ hở của rong rêu, tìm cách vươn mình ra dòng chảy chính.

Hành trình trôi dạt đưa Hạt Cát đi qua biết bao vùng đất lạ. Chú đi qua những bãi bồi trù phú, nơi những rặng tre xanh mướt ngả bóng xuống mặt sông. Chú lướt qua những bến đò nhộn nhịp tiếng cười nói của con người, đi qua những dải lụa phù sa đỏ nặng trĩu. Mỗi nơi đi qua, Hạt Cát lại học hỏi thêm được nhiều điều kỳ thú. Chú gặp được một bạn Cá Chép đang vượt vũ môn, nghe bạn ấy kể về lòng dũng cảm. Chú gặp một chiếc lá bàng đỏ ối rơi xuống mặt nước, nghe chiếc lá kể về sự luân hồi của sự sống. Tuy nhiên, hành trình không phải lúc nào cũng suôn sẻ. Có một lần, Hạt Cát bị trôi dạt vào một vũng nước đọng, nơi dòng chảy gần như tĩnh lặng. Chú nằm đó nhiều ngày, bị bao phủ bởi lớp bùn lầy đặc quánh. Nhiều hạt cát khác khuyên chú nên bỏ cuộc, ở lại vũng bùn này cho an toàn. Nhưng ý chí vươn ra biển lớn của Hạt Cát chưa bao giờ dập tắt. Chú kiên nhẫn đợi đến một ngày mưa bão lớn, dòng nước dâng cao tràn qua vũng lầy, Hạt Cát lại mạnh mẽ nương theo dòng nước để tiếp tục cuộc phiêu lưu.

Cứ thế, sau không biết bao nhiêu ngày tháng trôi qua, dòng sông dần trở nên rộng lớn hơn, dòng chảy cũng chậm rãi và điềm tĩnh hơn. Không khí bắt đầu mang theo một hương vị mằn mặn, và những cơn gió lồng lộng thổi đến, mang theo tiếng ầm ào xa xăm vang dội. Rồi một khoảnh khắc vỡ òa, dòng sông mở rộng vòng tay, hòa mình vào một khoảng không gian xanh thẳm, mênh mông vô tận. Đại Dương đây rồi! Hạt Cát sung sướng muốn hét lên. Chú trôi theo những con sóng bạc đầu, cảm nhận vị mặn mòi của biển cả thấm vào từng tinh thể. Chú ngắm nhìn những rặng san hô lung linh sắc màu dưới ánh nắng mặt trời xuyên thấu, bơi cùng những đàn cá chồn rực rỡ và thậm chí còn được một anh cua biển thân thiện chào hỏi. Trải qua muôn ngàn gian khó, cuối cùng Hạt Cát cũng chạm đến được ước mơ của đời mình. Chú nhận ra rằng, thế giới rộng lớn ngoài kia đẹp đẽ và kỳ vĩ hơn tất cả những gì cụ Rùa già đã kể, và mọi nỗ lực không ngừng nghỉ đều vô cùng xứng đáng.

Em bé ngoan của mẹ Như Ý, cuộc đời của mỗi con người cũng giống như chuyến du hành của Hạt Cát nhỏ dũng cảm kia. Từ lúc sinh ra cho đến khi khôn lớn, trưởng thành, con sẽ phải đối mặt với rất nhiều ngã rẽ, trải qua nhiều dòng chảy khác nhau. Sẽ có những lúc con được thả mình trôi êm đềm trên những bến bờ bình yên, nhưng cũng sẽ có những khoảnh khắc con gặp phải dòng nước xoáy, những vũng bùn lầy hay những hòn đá cản đường. Nhưng con đừng bao giờ sợ hãi nhé. Hãy giữ cho mình một trái tim đầy khát vọng và một ý chí kiên cường.

Mẹ Như Ý không thể theo sát để gạt bỏ mọi chướng ngại vật trên đường đời của con, nhưng mẹ hứa sẽ luôn là dòng sông hiền hòa mang theo những dưỡng chất tươi mát nhất để nuôi dưỡng tâm hồn con. Mẹ sẽ là người đứng trên bờ, dõi theo từng chặng đường con đi, cổ vũ cho mọi quyết định của con. Con hãy cứ tự tin vươn mình ra biển lớn, khám phá những chân trời mới lạ, học hỏi từ những người bạn gặp trên đường và xây dựng nên cuộc đời rực rỡ của chính mình. Dù con đi xa đến đâu, vòng tay của mẹ Như Ý và ba vẫn luôn là bến bờ bình yên nhất chờ đón con trở về. Yêu thương con thật nhiều, hạt cát vô giá của lòng mẹ!
""",
    
    "🎵 9. Bài Ca Từ Trái Tim Của Họa Mi": """
Câu chuyện 9: Bài ca từ trái tim của Họa Mi
Khu rừng Hòa Ca là nơi hội tụ của những giọng ca xuất sắc nhất trong thế giới loài chim. Cứ mỗi độ hoàng hôn buông xuống, khi ánh mặt trời nhuộm đỏ cả một góc trời phía tây, khu rừng lại trở thành một sân khấu âm nhạc khổng lồ. Anh chim Gõ Kiến mở đầu bằng những nhịp trống điêu luyện, gõ lách cách vào những thân cây mục rỗng. Cô chim Oanh cất tiếng hót lảnh lót, cao vút như những sợi tơ bạc lướt qua những tán lá. Bác chim Cu Gáy thì trầm ngâm với những âm điệu mộc mạc, ấm áp vang vọng khắp núi đồi. Khúc giao hưởng của núi rừng hòa quyện vào nhau, tạo nên một bản nhạc say đắm lòng người, tôn vinh vẻ đẹp của thiên nhiên.

Trong khu rừng ấy, có một cô chim Họa Mi nhỏ nhắn, sở hữu một bộ lông màu nâu nhạt giản dị, không sặc sỡ như chim Công, cũng chẳng mượt mà như chim Hoàng Yến. Họa Mi sinh ra với một cuống họng tuyệt vời, có khả năng phát ra những âm thanh vô cùng trong trẻo. Tuy nhiên, Họa Mi lại là một cô chim hay tự ti. Hằng ngày, khi lắng nghe buổi hòa nhạc của mọi người, Họa Mi luôn cảm thấy giọng hát của mình thật yếu ớt và đơn điệu. Cô ngưỡng mộ sự dẻo dai của chim Oanh, sự mạnh mẽ của Gõ Kiến và sự uy nghi của bác Đại Bàng trên đỉnh núi cao. Vì vậy, thay vì hót bằng giọng thật của mình, Họa Mi quyết định đi học hỏi và bắt chước giọng hót của những loài chim khác.

Ngày thứ nhất, Họa Mi bay đến chỗ chim Oanh để học cách luyến láy. Cô cố gắng vươn dài cổ, ép giọng mình phải thật cao và chói, nhưng kết quả chỉ phát ra những âm thanh thé thé, khiến cổ họng đau rát. Ngày thứ hai, Họa Mi đến tìm Gõ Kiến, cố gắng dùng chiếc mỏ nhỏ xíu của mình mổ vào thân cây cứng cáp để tạo nhịp điệu, hậu quả là chiếc mỏ sưng vù và đau nhức vô cùng. Ngày thứ ba, Họa Mi cố gắng bắt chước tiếng kêu hùng dũng của Đại Bàng, nhưng vì vóc dáng nhỏ bé, tiếng kêu của cô nghe giống như tiếng nấc nghẹn ngào hơn là tiếng thét của chúa tể bầu trời. Sau nhiều ngày cố gắng trở thành một bản sao của người khác, Họa Mi kiệt sức, cổ họng khản đặc, không thể phát ra bất kỳ âm thanh nào nữa. Cô tủi thân rúc vào một gốc cây tối tăm, thút thít khóc. Cô nghĩ rằng mình vĩnh viễn là một con chim vô dụng, không có tài năng gì đóng góp cho khu rừng.

Nghe tiếng khóc nấc của Họa Mi, một bác Cú Mèo già thông thái đang đậu trên cành thông già gần đó từ từ mở to đôi mắt tinh anh. Bác Cú Mèo bay xuống, dùng đôi cánh to lớn vỗ về cô chim nhỏ. "Họa Mi bé bỏng, vì sao cháu lại khóc lóc thảm thiết đến vậy?", bác Cú Mèo hỏi bằng giọng trầm ấm, uy nghiêm. Họa Mi nghẹn ngào kể lại câu chuyện của mình, về sự tự ti và những nỗ lực vô vọng trong việc thay đổi bản thân. Bác Cú Mèo mỉm cười hiền từ, lắc lư cái đầu khôn ngoan. "Cháu thật ngốc nghếch, Họa Mi ạ. Mỗi loài chim sinh ra đều được Đấng Tạo Hóa ban tặng một món quà riêng biệt. Chim Oanh hót cao vút vì tiếng hát của nó đại diện cho ánh nắng ban mai. Cu Gáy có giọng trầm ấm vì nó kể câu chuyện của đất đai màu mỡ. Còn cháu, cháu sinh ra để hót bằng chính trái tim của mình. Sự vay mượn không bao giờ mang lại giá trị thật sự. Cháu hãy tĩnh tâm lại, nhắm mắt và lắng nghe nhịp đập từ sâu thẳm lồng ngực mình. Chỉ khi cháu là chính mình, giọng hát của cháu mới thực sự có linh hồn".

Lời dạy của bác Cú Mèo như một luồng gió mát rượi thổi tan những đám mây u ám trong lòng Họa Mi. Cô nhắm mắt lại, hít một hơi thật sâu không khí trong lành của núi rừng, tạm quên đi những tiếng hót tài ba xung quanh. Cô tập trung lắng nghe tiếng xào xạc của lá rụng, tiếng róc rách của con suối nhỏ, và quan trọng nhất, là tiếng đập thình thịch, thổn thức của trái tim mình. Những cảm xúc chân thật nhất trào dâng. Họa Mi khẽ mở mỏ, một âm thanh nhỏ nhoi, êm ái vô tình thoát ra. Cô không gồng mình, không bắt chước, cứ để âm thanh tuôn trào một cách tự nhiên như suối nguồn. Giai điệu bắt đầu bay bổng, lúc trầm lúc bổng, da diết, sâu lắng và vô cùng thuần khiết. Giai điệu ấy chứa đựng nỗi buồn, niềm vui, sự tự do và cả tình yêu thương mãnh liệt với khu rừng. Tiếng hót của Họa Mi cất lên, xóa tan sự tĩnh lặng của màn đêm. Tất cả các loài chim khác đều ngừng hót, ngẩn ngơ lắng nghe. Giai điệu ấy chạm đến trái tim của mọi sinh linh, khiến những đóa hoa đêm cũng phải hé nở. Họa Mi đã tìm thấy giọng hát đích thực của mình, giọng hát đẹp nhất khi cô được là chính mình.

Con yêu dấu của mẹ Như Ý, câu chuyện của chim Họa Mi cũng là thông điệp sâu sắc nhất mà mẹ muốn gửi gắm đến con. Khi con khôn lớn và bước ra thế giới, con sẽ gặp rất nhiều người tài giỏi, xuất chúng. Sẽ có đôi lúc con cảm thấy mình thật nhỏ bé, và khao khát được giống như một ai đó để nhận được sự ngưỡng mộ. Nhưng con à, con không cần phải ép mình trở thành bản sao của bất kỳ ai. Sự vĩ đại thực sự không nằm ở việc con giống người khác bao nhiêu, mà nằm ở chỗ con dũng cảm thể hiện bản thân mình như thế nào.

Mỗi con người là một bản thể duy nhất và vô giá. Con có những thế mạnh riêng, những sở thích riêng và một trái tim mang nhịp đập của riêng con. Mẹ Như Ý và ba yêu con không phải vì con sẽ trở thành một người giống hệt kỳ vọng của xã hội, mà mẹ yêu con vì con là chính con, với tất cả những ưu điểm và khuyết điểm. Hãy cứ tự tin tỏa sáng bằng chính khả năng của mình, lắng nghe tiếng nói từ sâu thẳm trái tim để theo đuổi ước mơ. Dù giọng hát của con mang âm điệu gì đi chăng nữa, thì trong tai mẹ Như Ý, đó luôn là bài ca trong trẻo nhất, tuyệt vời nhất và đáng tự hào nhất. Hãy ngủ thật ngon và lớn lên trong sự tự do, kiêu hãnh nhé, chú chim họa mi bé bỏng của lòng mẹ!
"""
}

# Lời nhắn tương tác
MESSAGES = {
    "read_button": "Mẹ Như Ý đã đọc xong cho bé nghe! 🥰",
    "success_msg": "Bé con chắc chắn sẽ rất thích giọng đọc ấm áp của mẹ Như Ý! Chúc hai mẹ con một ngày thật vui vẻ nhé! 👼💖"
}
# --- THÊM PHẦN NÀY VÀO CUỐI FILE data.py ---

# Danh sách Kinh / Nhạc thai giáo
# Bạn có thể dùng link YouTube hoặc tên file .mp3 (nếu tải mp3 lên github)
AUDIOS = {
    "🪷 Kinh Phổ Môn (Giúp mẹ và bé bình an)": "https://www.youtube.com/watch?v=SFO2Xaku3uw", 
    "🪷 Kinh Địa Tạng (Giúp bé ngoan ngoãn, hiếu thảo)": "https://www.youtube.com/watch?v=TrWAdlXliyI",
    "🪷 Kinh Địa Tạng (Bình An, Cầu Con)": "https://www.youtube.com/watch?v=rlH1N-aA-v4",
    "🌿 Nhạc Thiền Nước Chảy Róc Rách (Thư giãn)": "https://www.youtube.com/watch?v=JJjb_WDWVJs"
}
