# Cấu hình giao diện
APP_SETTINGS = {
    "page_title": "Thai Giáo Cùng Như Ý",
    "page_icon": "👼",
    "main_title": "🌸 Góc Thai Giáo Của Như Ý 🌸",
    "subtitle": "Mỗi ngày một câu chuyện nhỏ, gửi gắm tình yêu to lớn cho thiên thần của mẹ 💖"
}

# Nơi dán nội dung truyện
STORIES = {
    "🌱 Hạt Mầm Kì Diệu": """
Câu chuyện 1: Chuyến Phiêu Lưu Của Hạt Mầm Kì Diệu
Trong một khu rừng sâu thẳm, nơi những bóng cây cổ thụ to lớn vươn những cánh tay rợp lá che chở cho vạn vật, có một phép màu nhỏ bé đang say ngủ. Khu rừng ấy không ồn ào hay náo nhiệt, mà mang một vẻ đẹp tĩnh lặng, êm đềm và vô cùng bình yên. Mỗi buổi sáng, khi ánh mặt trời đầu tiên chiếu rọi qua những kẽ lá, đánh thức những giọt sương mai còn đọng trên cành, khu rừng lại ngân lên một khúc ca trong trẻo của thiên nhiên. Tiếng chim lảnh lót hót vang gọi bầy, tiếng suối chảy róc rách len lỏi qua từng khe đá, và cả tiếng gió xạc xào đùa giỡn với những chiếc lá non. Tất cả tạo nên một bản giao hưởng tuyệt diệu, êm ái như một lời ru dịu dàng dành cho sinh linh bé nhỏ đang say giấc nồng dưới lớp đất nâu mềm mại.

Đó là một hạt mầm nhỏ xíu, tròn trịa và mang trong mình một sức sống mãnh liệt. Hạt mầm đã nằm đó từ rất lâu, được đất mẹ ôm ấp vào lòng, vỗ về bằng sự ấm áp và che chở khỏi những cơn gió lạnh lẽo của mùa đông. Đất mẹ hiền hòa, lúc nào cũng dịu dàng thủ thỉ vào tai hạt mầm những câu chuyện về thế giới bao la bên trên. Mẹ đất kể về bầu trời xanh ngắt cao vời vợi, về những đám mây trắng xốp như bông lững lờ trôi, về ánh nắng mặt trời rực rỡ mang lại sự sống cho muôn loài. Hạt mầm lắng nghe những câu chuyện ấy mỗi ngày, trong lòng trào dâng một khát khao mãnh liệt được vươn mình lên, được tự mắt nhìn ngắm thế giới rực rỡ mà đất mẹ vẫn thường hay kể.

Rồi một ngày, mùa xuân ấm áp gõ cửa khu rừng. Nàng tiên mùa xuân khoác lên mình chiếc váy kết từ muôn ngàn bông hoa rực rỡ, nhẹ nhàng lướt qua từng nhành cây, ngọn cỏ. Nàng mang theo những cơn mưa phùn lất phất, mỏng manh như sương, tưới mát cho vạn vật. Những giọt mưa xuân mang theo phép màu của sự sống, nhẹ nhàng thấm sâu vào lòng đất, đánh thức hạt mầm nhỏ đang say ngủ. Hạt mầm cựa mình, cảm nhận dòng nước mát lành đang chảy tràn qua từng tế bào. Nó vươn vai một cái thật dài, cảm thấy trong mình tràn trề một nguồn năng lượng mới mẻ, mạnh mẽ chưa từng có. Lớp vỏ cứng cáp bấy lâu nay che chở cho nó bắt đầu nứt ra, nhường chỗ cho một mầm non bé xíu, xanh mướt nhú lên.

Mầm non bắt đầu cuộc hành trình vĩ đại của cuộc đời mình: vươn lên mặt đất. Đó không phải là một chặng đường dễ dàng. Mầm non phải dùng hết sức lực nhỏ bé của mình để lách qua những kẽ đất tơi xốp, đôi khi gặp phải những viên sỏi cứng đầu cản đường. Nhưng mầm non không hề nản chí. Mỗi khi cảm thấy mệt mỏi, nó lại nhớ đến lời ru của đất mẹ, nhớ đến bầu trời xanh ngắt và ánh nắng chói chang đang chờ đợi mình ở phía trên. Những rễ non cũng bắt đầu cắm sâu vào lòng đất, hút lấy những dưỡng chất tinh túy nhất để nuôi dưỡng cơ thể, giúp mầm non ngày càng cứng cáp và mạnh mẽ hơn. Mỗi centimet vươn lên là một nỗ lực phi thường, là sự kiên cường và lòng dũng cảm đáng kinh ngạc của sinh linh bé nhỏ.

Cuối cùng, sau những ngày tháng nỗ lực không ngừng nghỉ, mầm non đã chạm đến lớp đất trên cùng. Một cú hích nhẹ nhàng, và rồi, bùm! Mầm non nhỏ xíu đã phá vỡ lớp đất, tự hào vươn mình ra khỏi bóng tối, đón chào thế giới ánh sáng. Khoảnh khắc đầu tiên khi mở mắt ra, mầm non bị choáng ngợp bởi vẻ đẹp lộng lẫy của vạn vật xung quanh. Mọi thứ còn rực rỡ và tươi đẹp hơn vạn lần so với những gì đất mẹ đã kể. Bầu trời quả thực xanh thẳm và rộng lớn vô tận. Ánh nắng mặt trời dịu dàng mơn trớn trên hai chiếc lá mầm non nớt, sưởi ấm cho nó sau những ngày dài dưới lòng đất lạnh. Một cơn gió thoảng qua, mang theo hương thơm ngai ngái của đất ẩm và mùi ngòn ngọt của những bông hoa rừng. Mầm non rung rinh trong gió, như một lời chào hỏi bẽn lẽn gửi đến thế giới bao la.

Một chú bướm với đôi cánh rực rỡ sắc màu bay lượn quanh mầm non, nhẹ nhàng đậu xuống chiếc lá xanh non nớt. "Chào mừng em đến với thế giới của chúng ta, sinh linh bé nhỏ!", chú bướm cất giọng trong trẻo. "Em đã làm rất tốt. Cuộc sống ngoài này vô cùng tuyệt vời, và em sẽ trở thành một cái cây thật xinh đẹp, mang lại bóng mát và niềm vui cho mọi người". Mầm non khẽ rung rung những chiếc lá, cảm thấy vô cùng hạnh phúc và tự hào. Nó biết rằng, cuộc hành trình của mình mới chỉ bắt đầu. Nó sẽ còn phải trải qua những ngày nắng gắt, những cơn mưa rào, những đợt gió lớn, nhưng nó không sợ hãi. Bởi vì nó biết, sâu thẳm bên dưới, đất mẹ vẫn luôn ôm ấp và nuôi dưỡng nó, bầu trời bao la vẫn luôn dang tay chào đón, và xung quanh nó là vô vàn những người bạn thiên nhiên tốt bụng.

Con yêu của mẹ, con cũng giống như hạt mầm nhỏ bé và dũng cảm kia vậy. Con đang say ngủ trong vòng tay ấm áp của mẹ, được mẹ che chở, yêu thương và nuôi dưỡng từng ngày. Mỗi ngày trôi qua, con lại lớn thêm một chút, khỏe mạnh hơn một chút. Mẹ biết, con cũng đang tò mò về thế giới bên ngoài, về những âm thanh con nghe thấy, về những cái chạm nhẹ nhàng qua lớp áo của mẹ. Thế giới ngoài kia rộng lớn và nhiều màu sắc lắm con ạ. Có mặt trời ấm áp, có những vì sao lấp lánh, có tiếng chim hót líu lo và có vòng tay yêu thương của ba mẹ đang chờ đón con.

Nhưng con đừng vội vã nhé. Hãy cứ an tâm say giấc, hấp thu những dưỡng chất ngọt ngào nhất từ tình yêu của mẹ, để chuẩn bị cho mình một cơ thể thật khỏe mạnh, một trái tim thật dũng cảm. Chặng đường phía trước của con sẽ là một cuộc phiêu lưu tuyệt vời nhất. Khi nào con sẵn sàng, hãy mạnh mẽ vươn mình ra thế giới, giống như hạt mầm kiên cường đã phá vỡ lớp đất nảy mầm. Ba mẹ sẽ ở đây, ngay khoảnh khắc đầu tiên con mở mắt, để dành cho con nụ cười ấm áp nhất và cái ôm chặt nhất. Hãy lớn lên thật bình an, sinh linh bé nhỏ và kỳ diệu của ba mẹ. Mẹ yêu con rất nhiều, yêu hơn bất cứ điều gì trên thế gian này.
""",
    
    "☁️ Đám Mây Nhỏ Đi Tìm Ý Nghĩa": """
Câu chuyện 2: Đám Mây Nhỏ Đi Tìm Ý Nghĩa Cuộc Sống
Trên bầu trời cao vời vợi, nơi không gian trong vắt như một viên pha lê khổng lồ, có một gia đình mây sinh sống. Những đám mây to lớn, trắng muốt như những chiếc kẹo bông gòn lơ lửng giữa không trung. Trong gia đình ấy, có một đám mây nhỏ xíu, bé bé xinh xinh và lúc nào cũng mang trong mình vô vàn câu hỏi. Trong khi các anh chị mây lớn thích lững lờ trôi theo chiều gió, thong dong ngắm nhìn thế giới từ trên cao hay tụ tập lại thành những hình thù ngộ nghĩnh, thì đám mây nhỏ lại không ngừng băn khoăn về sự tồn tại của chính mình. "Mình sinh ra để làm gì nhỉ?", đám mây nhỏ tự hỏi. "Chẳng lẽ chỉ để lơ lửng trôi trên bầu trời mãi như thế này sao?".

Một ngày nọ, đám mây nhỏ quyết định xin phép mẹ gió để bắt đầu một cuộc hành trình đi tìm ý nghĩa cuộc sống của mình. Mẹ gió hiền từ mỉm cười, thổi một luồng hơi nhẹ nhàng đẩy đám mây nhỏ trôi đi. "Hãy đi đi con yêu, hãy dùng trái tim của mình để cảm nhận thế giới, con sẽ tìm thấy câu trả lời", mẹ gió dặn dò. Thế là đám mây nhỏ háo hức bắt đầu chuyến phiêu lưu đầu tiên. Nó trôi qua những ngọn núi cao chót vót, quanh năm tuyết phủ trắng xóa. Những đỉnh núi sắc nhọn như muốn chọc thủng bầu trời, kiêu hãnh đứng giữa đất trời. Đám mây nhỏ sà xuống thấp một chút, rụt rè hỏi: "Bác núi ơi, bác có biết cháu sinh ra để làm gì không?". Ngọn núi ầm ầm đáp lại bằng một giọng trầm đục: "Ta không biết, hỡi mây nhỏ. Nhiệm vụ của ta là đứng vững ở đây, che chắn những cơn bão và tạo ra những dòng suối từ băng tuyết tan. Trách nhiệm của mỗi loài là khác nhau, cháu phải tự mình khám phá thôi".

Đám mây nhỏ lại tiếp tục bay đi. Nó trôi qua một cánh đồng hoa hướng dương rực rỡ dưới ánh nắng mặt trời. Hàng vạn bông hoa vàng ươm đang cùng nhau ngước nhìn lên bầu trời, tạo thành một thảm màu vàng rực rỡ đến lóa mắt. Đám mây nhỏ ngẩn ngơ trước vẻ đẹp ấy, nó hỏi một bông hoa hướng dương cao lớn nhất: "Bạn hoa ơi, bạn có biết mình sinh ra để làm gì không?". Bông hoa rung rinh trong gió, đáp lại bằng một giọng thanh thúy: "Tớ sinh ra để đón ánh nắng mặt trời, để tỏa hương sắc cho đời và mang lại hạt mầm cho mùa sau. Cậu hãy thử bay đến những nơi đang cần sự giúp đỡ xem sao, biết đâu cậu sẽ tìm thấy ý nghĩa của mình ở đó". Lời khuyên của bông hoa hướng dương làm đám mây nhỏ bừng tỉnh. Nó quyết định nhờ bác gió đưa mình đến những vùng đất xa xôi hơn.

Bác gió thổi mạnh, đưa đám mây nhỏ vượt qua những cánh rừng xanh mướt, những dòng sông êm đềm, cho đến khi nó đến một vùng đất khô cằn, nứt nẻ. Ở đây, mặt trời chiếu những tia nắng chói chang, gay gắt như muốn thiêu đốt mọi thứ. Cây cối héo hon, rũ rượi, những chiếc lá vàng vọt rụng lả tả. Dưới mặt đất, những con vật nhỏ bé đang khát khô cổ, mệt mỏi nằm bẹp dưới những bóng râm nhỏ nhoi còn sót lại. Một cái cây khô héo thều thào gọi: "Nước... chúng tôi cần nước...". Trái tim của đám mây nhỏ thắt lại. Nó chưa bao giờ nhìn thấy một cảnh tượng nào đáng thương đến thế. Nó muốn giúp đỡ họ, nhưng nó chỉ là một đám mây nhỏ bé, bồng bềnh, làm sao có thể mang lại nước cho cả một vùng đất rộng lớn này?

Đúng lúc đó, đám mây nhỏ nhớ lại lời dạy của mẹ gió: "Hãy dùng trái tim của mình để cảm nhận". Nó nhắm mắt lại, dồn hết sức lực và tình yêu thương của mình, cố gắng tập trung mọi luồng không khí ẩm ướt xung quanh. Bỗng nhiên, từ một đám mây trắng xốp, nó bắt đầu chuyển sang màu xám sẫm. Nó cảm thấy cơ thể mình nặng trĩu, chứa đầy những giọt nước mát lành. Không chần chừ thêm giây phút nào, đám mây nhỏ bung mình ra, hóa thành vô vàn những hạt mưa trong vắt, tuôn rơi xuống mặt đất khô cằn.

"Mưa rồi! Mưa rồi!", muôn loài reo hò trong sung sướng. Những hạt mưa mát lạnh rơi xuống, tưới tắm cho cỏ cây, lấp đầy những khe nẻ của đất. Cây cối như bừng tỉnh sau một giấc ngủ dài, vươn những cành lá xanh tươi đón nhận dòng nước ngọt ngào. Những con vật nhỏ bé vui sướng uống những ngọn nước hiếm hoi, nhảy múa dưới cơn mưa vô cùng thích thú. Đất trời như được khoác lên một chiếc áo mới, tràn đầy sức sống và hy vọng. Đám mây nhỏ không còn tồn tại dưới hình hài một đám mây nữa, nhưng nó không hề buồn bã. Bởi vì, nó đang hòa mình vào từng cái cây, từng ngọn cỏ, từng dòng suối nhỏ. Nó đã hiểu được ý nghĩa thực sự của cuộc đời mình: đó là sự hy sinh, là mang lại sự sống và niềm vui cho muôn loài.

Con yêu của ba mẹ, câu chuyện của đám mây nhỏ cũng là một bài học tuyệt vời về tình yêu thương và sự sẻ chia. Mỗi sinh mệnh khi sinh ra trên cõi đời này đều mang một ý nghĩa đặc biệt, và ý nghĩa cao đẹp nhất chính là biết yêu thương và mang lại hạnh phúc cho những người xung quanh. Con đang lớn lên từng ngày trong cơ thể mẹ, cảm nhận được từng nhịp đập trái tim mẹ, cảm nhận được tình yêu bao la mà ba mẹ dành cho con. Tình yêu ấy giống như những giọt mưa mát lành tưới tắm cho mầm non, nuôi dưỡng con trở thành một em bé khỏe mạnh, vui vẻ và ngoan ngoãn.

Ba mẹ không mong ước gì cao xa, chỉ mong con khi sinh ra sẽ là một em bé có trái tim ấm áp, biết yêu thương muôn loài, biết chia sẻ niềm vui với những người xung quanh. Hãy giống như đám mây nhỏ, dù nhỏ bé nhưng mang trong mình một tình yêu to lớn, sẵn sàng hóa thành cơn mưa tưới mát cho những tâm hồn đang khô cằn. Nhưng trước khi làm được những điều vĩ đại đó, con hãy ngoan ngoãn nằm trong bụng mẹ nhé, ăn thật no, ngủ thật say để lớn lên cứng cáp. Ba mẹ sẽ luôn là bầu trời bao la, là ngọn gió hiền hòa, che chở và dìu dắt con trên mỗi bước đường đời. Ngủ ngoan nhé, thiên thần bé nhỏ của ba mẹ. Cả thế giới đang mong chờ ngày con chào đời, mang theo ánh sáng và tình yêu thương đến với gia đình chúng ta.
""",
    
    "🌊 Bản Giao Hưởng Đại Dương": """
Câu chuyện 3: Bản Giao Hưởng Của Đại Dương Xanh
Sâu thẳm dưới những con sóng bạc đầu của đại dương bao la, có một thế giới bí ẩn và tuyệt diệu ẩn mình. Đó không phải là một thế giới tối tăm và tĩnh lặng như nhiều người vẫn tưởng tượng, mà là một vương quốc vô cùng rực rỡ, tràn ngập ánh sáng, màu sắc và những âm thanh kỳ diệu. Dưới tầng nước trong vắt như pha lê, ánh nắng mặt trời xuyên qua tạo thành những dải ánh sáng lung linh, nhảy múa trên những rặng san hô nhiều màu sắc. San hô đỏ chót như những cụm hoa nở rộ, san hô xanh biếc như những tán cây dưới nước, san hô tím mộng mơ đung đưa theo từng nhịp sóng. Chúng tạo thành một khu rừng dưới đáy biển, nơi trú ngụ của hàng ngàn loài sinh vật biển với muôn hình vạn trạng.

Trong vương quốc đại dương ấy, có một chú cá Heo nhỏ tên là Fin. Fin là một chú cá Heo vô cùng thông minh, hiếu động và có một đôi mắt to tròn, lấp lánh như hai hòn bi ve. Khác với những người bạn cùng trang lứa chỉ thích đuổi bắt nhau quanh những rặng san hô, Fin lại có một niềm đam mê mãnh liệt với những âm thanh. Chú yêu thích tiếng nước chảy róc rách qua các khe đá, tiếng cọ xát nhẹ nhàng của những chiếc vỏ sò trên bãi cát trắng, và đặc biệt là tiếng hát du dương của bác Cá Voi xanh vọng lại từ phương xa. Đối với Fin, mỗi âm thanh dưới đại dương đều là một nốt nhạc tuyệt vời, và chú luôn ao ước có thể tạo ra một bản giao hưởng trọn vẹn của riêng mình.

Một ngày nọ, Fin quyết định sẽ tổ chức một buổi hòa nhạc lớn nhất từ trước đến nay để dành tặng cho nữ hoàng Biển Cả nhân ngày sinh nhật của bà. Chú bơi khắp nơi, mời gọi những người bạn tài năng nhất trong vương quốc đại dương tham gia vào ban nhạc của mình. Đầu tiên, Fin đến gặp anh bạn Tôm Hùm gai góc. Dù vẻ ngoài có vẻ bặm trợn, nhưng Tôm Hùm lại có đôi càng gõ nhịp cực kỳ điêu luyện. "Anh Tôm Hùm ơi, anh có muốn tham gia vào ban nhạc của em không? Những nhịp gõ của anh chắc chắn sẽ làm nền tảng vững chắc cho bản giao hưởng của chúng ta đấy!", Fin hào hứng nói. Tôm Hùm đồng ý ngay lập tức, vung vẩy đôi càng tạo ra những tiếng "lách cách" vui tai.

Tiếp theo, Fin mời bầy Cá Ngựa tham gia. Những chú cá ngựa nhỏ bé, với chiếc đuôi xoắn ốc xinh xắn, có khả năng di chuyển lên xuống vô cùng nhịp nhàng. Chúng sẽ hóa thân thành những vũ công điệu nghệ, tạo ra những âm thanh vút cao như tiếng đàn vĩ cầm khi lướt qua những luồng nước. Rồi Fin tìm đến những cô Sứa biển mềm mại, trong suốt. Những chiếc tua dài của các cô Sứa khi khẽ chạm vào nhau tạo ra những âm thanh rinh rích, mờ ảo như tiếng chuông gió ngân vang trong buổi chiều tà. Cuối cùng, để bản giao hưởng thêm phần hoành tráng, Fin đã dũng cảm bơi ra vùng nước sâu, kính cẩn mời bác Cá Voi xanh tham gia bằng giọng hát trầm ấm, vang vọng xuyên đại dương của mình.

Những ngày sau đó, cả ban nhạc dưới sự chỉ huy của nhạc trưởng Fin ngày đêm tập luyện say sưa. Ban đầu, mọi thứ còn khá lộn xộn. Tiếng gõ càng của anh Tôm Hùm đi lệch nhịp với bầy Cá Ngựa, còn giọng hát của bác Cá Voi xanh thì lại át mất tiếng chuông gió mỏng manh của các cô Sứa. Nhưng Fin không hề nản lòng. Bằng sự kiên nhẫn, tình yêu âm nhạc và tài năng chỉ huy của mình, chú dần dần kết nối mọi người lại với nhau. Chú lắng nghe từng âm thanh, điều chỉnh từng nhịp điệu, giúp các thành viên thấu hiểu và hòa quyện vào nhau. Chẳng bao lâu sau, những âm thanh rời rạc đã biến thành một bản nhạc hoàn chỉnh, êm ái, sâu lắng nhưng cũng vô cùng hùng tráng và tráng lệ.

Ngày sinh nhật của nữ hoàng Biển Cả cũng đến. Toàn bộ cư dân của vương quốc đại dương đều tụ tập đông đủ tại quảng trường San Hô để thưởng thức buổi hòa nhạc. Khi Fin đưa chiếc vây nhỏ của mình lên, báo hiệu bắt đầu, cả đại dương dường như chìm vào tĩnh lặng. Rồi từ từ, những nhịp gõ chắc nịch của anh Tôm Hùm vang lên, nhịp nhàng và lôi cuốn. Tiếp đó là sự tham gia của bầy Cá Ngựa, mang đến những giai điệu vui tươi, rộn rã. Các cô Sứa biển nhẹ nhàng điểm xuyết những tiếng chuông ngân nga, thanh thúy. Và cuối cùng, giọng hát trầm hùng, ấm áp của bác Cá Voi xanh vang lên, ôm trọn lấy tất cả mọi âm thanh, tạo nên một bản giao hưởng vĩ đại, lay động mọi trái tim. Bản nhạc kể về vẻ đẹp của đại dương, về tình yêu thương, sự đoàn kết và niềm vui của cuộc sống. Nữ hoàng Biển Cả xúc động rơi những giọt nước mắt trân châu rực rỡ, bà khen ngợi Fin và ban nhạc đã mang đến món quà tuyệt vời nhất.

Con yêu của mẹ, con có đang lắng nghe bản giao hưởng của sự sống ngay lúc này không? Trong thế giới tĩnh lặng bên trong bụng mẹ, con cũng đang được đắm mình trong những âm thanh kỳ diệu. Đó là tiếng nhịp tim đập thình thịch, mạnh mẽ và đều đặn của mẹ, giống như những nhịp gõ vững chãi của anh Tôm Hùm, báo hiệu sự sống đang tuôn chảy không ngừng. Đó là tiếng dòng máu chảy qua các huyết quản, êm đềm như tiếng bầy Cá Ngựa lướt đi trong nước. Và đó còn là tiếng thủ thỉ dịu dàng, tiếng hát ru êm ái của ba mẹ mỗi đêm, giống như giọng hát ấm áp của bác Cá Voi xanh, bao bọc và chở che con khỏi mọi bão giông.

Những âm thanh ấy chính là bản giao hưởng tuyệt vời nhất mà ba mẹ dành riêng cho con, để nuôi dưỡng tâm hồn con trở nên phong phú, nhạy cảm và tràn đầy tình yêu thương. Ba mẹ muốn con biết rằng, dù thế giới ngoài kia có ồn ào và náo nhiệt đến đâu, thì trong trái tim ba mẹ, con luôn là giai điệu êm ái nhất, bình yên nhất. Hãy cứ nhắm mắt lại, thư giãn và tận hưởng bản nhạc của tình mẫu tử, tình phụ tử thiêng liêng này con nhé. Mỗi một ngày trôi qua, bản giao hưởng ấy sẽ càng trở nên mạnh mẽ và rõ ràng hơn, chào đón ngày con cất tiếng khóc chào đời, gia nhập vào dàn đồng ca rực rỡ của cuộc sống. Ngủ ngon nhé, nhạc trưởng tài ba bé nhỏ của ba mẹ!
"""
}

# Lời nhắn tương tác
MESSAGES = {
    "read_button": "Mẹ Như Ý đã đọc xong cho bé nghe! 🥰",
    "success_msg": "Bé con chắc chắn sẽ rất thích giọng đọc ấm áp của mẹ Như Ý! Chúc hai mẹ con một ngày thật vui vẻ nhé! 👼💖"
}